# Generated by Django 5.0.3 on 2024-04-21 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmacia',
            old_name='uid',
            new_name='id_farma',
        ),
        migrations.RemoveField(
            model_name='farmauser',
            name='test',
        ),
        migrations.AddField(
            model_name='farmauser',
            name='farma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.farmacia'),
        ),
    ]
