# Generated by Django 5.0.4 on 2024-05-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='nombre1',
            field=models.CharField(default='nombre', max_length=100),
        ),
    ]
