# Generated by Django 5.0.4 on 2024-05-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_farmacia_nombre1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacia',
            name='nombre1',
        ),
    ]
