# Generated by Django 5.0.3 on 2024-05-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_uid_farmacia_id_farma_remove_farmauser_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmauser',
            name='farma',
        ),
        migrations.AddField(
            model_name='farmauser',
            name='prueba',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
