# Generated by Django 5.0.4 on 2024-05-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_farmaciamedicamento_id_farmacia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmaciamedicamento',
            name='id_medic',
        ),
    ]
