# Generated by Django 5.0.4 on 2024-05-12 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_farmaciamedicamento_id_medic'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmaciamedicamento',
            name='id_farmacia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.farmacia'),
        ),
    ]
