# Generated by Django 5.0.4 on 2024-05-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_farmacia_nombre1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmacia',
            old_name='id_farma',
            new_name='farma_id',
        ),
    ]
