# Generated by Django 5.0.3 on 2024-05-11 22:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_farmauser_farma_farmauser_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacia',
            name='id',
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='id_farma',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
