# Generated by Django 5.0.3 on 2024-05-11 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_farmacia_id_alter_farmacia_id_farma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmauser',
            name='prueba',
        ),
        migrations.AddField(
            model_name='farmauser',
            name='id_farma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.farmacia'),
        ),
    ]
