# Generated by Django 5.0.4 on 2024-05-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_id_farma_farmacia_farma_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmauser',
            name='farma',
        ),
        migrations.AddField(
            model_name='farmauser',
            name='nombre1',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
