# Generated by Django 5.0.4 on 2024-05-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_farmaciamedicamento_id_farmacia'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmaciamedicamento',
            name='id_medic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.medicamento'),
        ),
    ]
