# Generated by Django 5.0.4 on 2024-05-11 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_farmauser_farma_farmauser_nombre1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmauser',
            name='nombre1',
        ),
        migrations.AddField(
            model_name='farmauser',
            name='farma_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.farmacia'),
        ),
    ]
