# Generated by Django 5.0.4 on 2024-05-12 23:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_farmaciamedicamento_id_medic'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
