# Generated by Django 5.0.4 on 2024-05-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_farmauser_nombre1_farmauser_farma_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmacia',
            old_name='farma_id',
            new_name='id_farma',
        ),
    ]
