# Generated by Django 5.0.3 on 2024-05-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_farmauser_id_farma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmaciamedicamento',
            name='id_farmacia',
        ),
        migrations.RemoveField(
            model_name='farmaciamedicamento',
            name='id_medic',
        ),
    ]
