# Generated by Django 5.0.4 on 2024-05-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_farma_id_farmacia_id_farma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmauser',
            old_name='farma_id',
            new_name='id_farma',
        ),
    ]
