# Generated by Django 5.0.3 on 2024-05-12 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_farmaciamedicamento_id_farmacia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmaciamedicamento',
            name='id_farma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.farmacia'),
        ),
        migrations.AddField(
            model_name='farmaciamedicamento',
            name='id_medic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.medicamento'),
        ),
    ]
