# Generated by Django 5.0.3 on 2024-05-14 01:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_farmaciamedicamento_id_farma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestriccionMedicamento',
            fields=[
                ('id_restriccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='TipoMedicamento',
            new_name='ClasificacionMedicamento',
        ),
        migrations.RenameField(
            model_name='clasificacionmedicamento',
            old_name='id_tipo_medicamento',
            new_name='id_clasificacion',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='id_restriccion',
        ),
    ]
