# Generated by Django 5.0.4 on 2024-05-11 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_farma_id_farmauser_id_farma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmauser',
            name='id_farma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.farmacia'),
        ),
    ]
