# Generated by Django 5.0.3 on 2024-05-14 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_restriccionmedicamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='id_clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.clasificacionmedicamento'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_restriccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.restriccionmedicamento'),
        ),
    ]
