# Generated by Django 5.0.3 on 2024-05-15 02:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_medicamento_id_clasificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacia',
            name='is_active',
        ),
        migrations.AddField(
            model_name='farmacia',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
