# Generated by Django 5.0.3 on 2024-05-26 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_farmacia_is_active_farmacia_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoMedicamento',
            fields=[
                ('id_formato', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_formato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.formatomedicamento'),
        ),
    ]
