# Generated by Django 5.0.3 on 2024-05-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_medicamento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
