# Generated by Django 5.0.3 on 2024-05-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_medicamento_fecha_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='reacciones',
            field=models.ManyToManyField(blank=True, related_name='reacciones_con', to='base.medicamento'),
        ),
    ]
