# Generated by Django 5.0.3 on 2024-05-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_medicamento_reacciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='fecha_expiracion',
        ),
        migrations.AddField(
            model_name='farmaciamedicamento',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
