# Generated by Django 5.0.3 on 2024-05-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_medicamento_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='reacciones',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='reacciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
