# Generated by Django 5.0.3 on 2024-06-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_tareaexistencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareaexistencia',
            old_name='medicamento',
            new_name='id_medic',
        ),
        migrations.RenameField(
            model_name='tareaexistencia',
            old_name='user',
            new_name='id_user',
        ),
    ]
