# Generated by Django 5.0.3 on 2024-06-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_clasificacionmedicamento_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipofarmacia',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
