# Generated by Django 5.0.3 on 2024-06-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_tipofarmacia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipofarmacia',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
