# Generated by Django 5.0.3 on 2024-06-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_tipofarmacia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
