# Generated by Django 5.0.3 on 2024-06-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_farmaciamedicamento_fecha_expiracion_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
